CollectAllIntel()
{
    self PrintHint("^3开始收集情报（录音/神器/文件）");
    if (!isdefined(self.var_9d781602))
        self.var_9d781602 = [];

    names = IntelNameList();
    total = names.size;
    n = 0;
    foreach (hid in names)
    {
        if (!self zm_stats::function_376778d3(hid))
        {
            self zm_intel::function_7e211a10(hid);
            self zm_stats::function_a6b15f2c(hid, 1);
            if (!isinarray(self.var_9d781602, hid))
                self.var_9d781602[self.var_9d781602.size] = hid;
        }
        n++;
        if (n % 20 == 0)
        {
            self PrintHint("^5情报 " + n + "/" + total);
            wait 0.1;
        }
    }
    uploadstats(self);
    self PrintHint("^5解锁情报 ^2" + total);
}

IntelNameList()
{
    names = [];
    names = IntelPush(names, array(#"zmintel_dune_omega_document_1", #"zmintel_dune_omega_document_2", #"zmintel_dune_omega_document_3", #"zmintel_gold_darkaether_artifact_1", #"zmintel_gold_darkaether_audiolog_1", #"zmintel_gold_darkaether_audiolog_2", #"zmintel_gold_darkaether_audiolog_3", #"zmintel_gold_darkaether_audiolog_4", #"zmintel_gold_darkaether_audiolog_5", #"zmintel_gold_darkaether_document_1", #"zmintel_gold_darkaether_document_10", #"zmintel_gold_darkaether_document_11", #"zmintel_gold_darkaether_document_12", #"zmintel_gold_darkaether_document_13", #"zmintel_gold_darkaether_document_2", #"zmintel_gold_darkaether_document_3", #"zmintel_gold_darkaether_document_4"));
    names = IntelPush(names, array(#"zmintel_gold_darkaether_document_5", #"zmintel_gold_darkaether_document_6", #"zmintel_gold_darkaether_document_7", #"zmintel_gold_darkaether_document_8", #"zmintel_gold_darkaether_document_9", #"zmintel_gold_darkaether_radio_1", #"zmintel_gold_darkaether_radio_2", #"zmintel_gold_maxis_audiolog_1", #"zmintel_gold_maxis_audiolog_2", #"zmintel_gold_maxis_audiolog_3", #"zmintel_gold_maxis_audiolog_4", #"zmintel_gold_maxis_document_1", #"zmintel_gold_maxis_document_2", #"zmintel_gold_maxis_document_3", #"zmintel_gold_maxis_document_4", #"zmintel_gold_maxis_radio_1", #"zmintel_gold_maxis_radio_2", #"zmintel_gold_maxis_radio_3", #"zmintel_gold_maxis_radio_4"));
    names = IntelPush(names, array(#"zmintel_gold_maxis_radio_5", #"zmintel_gold_maxis_radio_6", #"zmintel_gold_maxis_radio_7", #"zmintel_gold_maxis_radio_8", #"zmintel_gold_maxis_radio_9", #"zmintel_gold_omega_artifact_1", #"zmintel_gold_omega_artifact_2", #"zmintel_gold_omega_artifact_3", #"zmintel_gold_omega_artifact_4", #"zmintel_gold_omega_artifact_5", #"zmintel_gold_omega_audiolog_1", #"zmintel_gold_omega_audiolog_2", #"zmintel_gold_omega_audiolog_3", #"zmintel_gold_omega_audiolog_4", #"zmintel_gold_omega_audiolog_5", #"zmintel_gold_omega_audiolog_6", #"zmintel_gold_omega_audiolog_7", #"zmintel_gold_omega_audiolog_8", #"zmintel_gold_omega_audiolog_9", #"zmintel_gold_omega_document_1"));
    names = IntelPush(names, array(#"zmintel_gold_omega_document_2", #"zmintel_gold_omega_document_3", #"zmintel_gold_omega_document_4", #"zmintel_gold_omega_document_5", #"zmintel_gold_omega_document_6", #"zmintel_gold_omega_radio_1", #"zmintel_gold_omega_radio_2", #"zmintel_gold_omega_radio_3", #"zmintel_gold_omega_radio_4", #"zmintel_gold_omega_radio_5", #"zmintel_gold_requiem_artifact_1", #"zmintel_gold_requiem_artifact_2", #"zmintel_gold_requiem_artifact_3", #"zmintel_gold_requiem_artifact_4", #"zmintel_gold_requiem_audiolog_1", #"zmintel_gold_requiem_audiolog_2", #"zmintel_gold_requiem_audiolog_3", #"zmintel_gold_requiem_audiolog_4", #"zmintel_gold_requiem_document_1"));
    names = IntelPush(names, array(#"zmintel_gold_requiem_document_2", #"zmintel_gold_requiem_document_3", #"zmintel_gold_requiem_document_4", #"zmintel_gold_requiem_document_5", #"zmintel_gold_requiem_document_6", #"zmintel_gold_requiem_document_7", #"zmintel_gold_requiem_radio_1", #"zmintel_gold_requiem_radio_10", #"zmintel_gold_requiem_radio_11", #"zmintel_gold_requiem_radio_12", #"zmintel_gold_requiem_radio_13", #"zmintel_gold_requiem_radio_2", #"zmintel_gold_requiem_radio_3", #"zmintel_gold_requiem_radio_4", #"zmintel_gold_requiem_radio_5", #"zmintel_gold_requiem_radio_6", #"zmintel_gold_requiem_radio_7", #"zmintel_gold_requiem_radio_8", #"zmintel_gold_requiem_radio_9"));
    names = IntelPush(names, array(#"zmintel_platinum_darkaether_artifact_01", #"zmintel_platinum_darkaether_artifact_02", #"zmintel_platinum_darkaether_artifact_03", #"zmintel_platinum_darkaether_audiolog_01", #"zmintel_platinum_darkaether_audiolog_02", #"zmintel_platinum_darkaether_audiolog_03", #"zmintel_platinum_darkaether_document_01", #"zmintel_platinum_darkaether_document_02", #"zmintel_platinum_darkaether_document_03", #"zmintel_platinum_darkaether_radio_01", #"zmintel_platinum_darkaether_radio_02", #"zmintel_platinum_omega_artifact_01", #"zmintel_platinum_omega_artifact_02", #"zmintel_platinum_omega_audiolog_01", #"zmintel_platinum_omega_audiolog_02", #"zmintel_platinum_omega_audiolog_03"));
    names = IntelPush(names, array(#"zmintel_platinum_omega_document_01", #"zmintel_platinum_omega_document_02", #"zmintel_platinum_omega_document_03", #"zmintel_platinum_omega_document_04", #"zmintel_platinum_omega_document_05", #"zmintel_platinum_omega_document_06", #"zmintel_platinum_omega_radio_01", #"zmintel_platinum_omega_radio_02", #"zmintel_platinum_omega_radio_03", #"zmintel_platinum_omega_radio_04", #"zmintel_platinum_omega_radio_05", #"zmintel_platinum_requiem_artifact_01", #"zmintel_platinum_requiem_artifact_02", #"zmintel_platinum_requiem_artifact_03", #"zmintel_platinum_requiem_artifact_04", #"zmintel_platinum_requiem_artifact_05", #"zmintel_platinum_requiem_artifact_06"));
    names = IntelPush(names, array(#"zmintel_platinum_requiem_audiolog_01", #"zmintel_platinum_requiem_audiolog_02", #"zmintel_platinum_requiem_audiolog_03", #"zmintel_platinum_requiem_audiolog_04", #"zmintel_platinum_requiem_audiolog_05", #"zmintel_platinum_requiem_document_01", #"zmintel_platinum_requiem_document_02", #"zmintel_platinum_requiem_document_03", #"zmintel_platinum_requiem_document_04", #"zmintel_platinum_requiem_document_05", #"zmintel_platinum_requiem_document_06", #"zmintel_platinum_requiem_document_07", #"zmintel_platinum_requiem_document_08", #"zmintel_platinum_requiem_document_09", #"zmintel_platinum_requiem_document_10", #"zmintel_silver_darkaether_artifact_1"));
    names = IntelPush(names, array(#"zmintel_silver_darkaether_artifact_2", #"zmintel_silver_darkaether_artifact_3", #"zmintel_silver_darkaether_artifact_4", #"zmintel_silver_darkaether_audiolog_1", #"zmintel_silver_darkaether_audiolog_2", #"zmintel_silver_darkaether_audiolog_3", #"zmintel_silver_darkaether_audiolog_4", #"zmintel_silver_darkaether_audiolog_5", #"zmintel_silver_darkaether_audiolog_6", #"zmintel_silver_darkaether_audiolog_7", #"zmintel_silver_darkaether_audiolog_8", #"zmintel_silver_darkaether_document_1", #"zmintel_silver_darkaether_document_10", #"zmintel_silver_darkaether_document_11", #"zmintel_silver_darkaether_document_12", #"zmintel_silver_darkaether_document_13"));
    names = IntelPush(names, array(#"zmintel_silver_darkaether_document_14", #"zmintel_silver_darkaether_document_15", #"zmintel_silver_darkaether_document_2", #"zmintel_silver_darkaether_document_3", #"zmintel_silver_darkaether_document_4", #"zmintel_silver_darkaether_document_5", #"zmintel_silver_darkaether_document_6", #"zmintel_silver_darkaether_document_7", #"zmintel_silver_darkaether_document_8", #"zmintel_silver_darkaether_document_9", #"zmintel_silver_darkaether_radio_1", #"zmintel_silver_darkaether_radio_2", #"zmintel_silver_darkaether_radio_3", #"zmintel_silver_darkaether_radio_4", #"zmintel_silver_darkaether_radio_5", #"zmintel_silver_maxis_audiolog_1", #"zmintel_silver_maxis_audiolog_2"));
    names = IntelPush(names, array(#"zmintel_silver_maxis_audiolog_3", #"zmintel_silver_maxis_document_1", #"zmintel_silver_maxis_document_2", #"zmintel_silver_maxis_document_3", #"zmintel_silver_maxis_radio_1", #"zmintel_silver_maxis_radio_2", #"zmintel_silver_maxis_radio_3", #"zmintel_silver_maxis_radio_4", #"zmintel_silver_maxis_radio_5", #"zmintel_silver_maxis_radio_6", #"zmintel_silver_omega_artifact_1", #"zmintel_silver_omega_audiolog_1", #"zmintel_silver_omega_audiolog_2", #"zmintel_silver_omega_audiolog_3", #"zmintel_silver_omega_audiolog_4", #"zmintel_silver_omega_audiolog_5", #"zmintel_silver_omega_document_1", #"zmintel_silver_omega_document_2", #"zmintel_silver_omega_document_3"));
    names = IntelPush(names, array(#"zmintel_silver_omega_document_4", #"zmintel_silver_omega_document_5", #"zmintel_silver_omega_document_6", #"zmintel_silver_omega_document_7", #"zmintel_silver_requiem_artifact_1", #"zmintel_silver_requiem_artifact_2", #"zmintel_silver_requiem_artifact_3", #"zmintel_silver_requiem_artifact_4", #"zmintel_silver_requiem_artifact_5", #"zmintel_silver_requiem_audiolog_1", #"zmintel_silver_requiem_audiolog_2", #"zmintel_silver_requiem_audiolog_3", #"zmintel_silver_requiem_audiolog_4", #"zmintel_silver_requiem_document_1", #"zmintel_silver_requiem_document_2", #"zmintel_silver_requiem_document_3", #"zmintel_silver_requiem_document_4", #"zmintel_silver_requiem_document_5"));
    names = IntelPush(names, array(#"zmintel_silver_requiem_document_6", #"zmintel_silver_requiem_document_7", #"zmintel_silver_requiem_radio_1", #"zmintel_silver_requiem_radio_2", #"zmintel_silver_requiem_radio_3", #"zmintel_silver_requiem_radio_4", #"zmintel_silver_requiem_radio_5", #"zmintel_silver_requiem_radio_6", #"zmintel_silver_requiem_radio_7", #"zmintel_survival_darkaether_artifact_1", #"zmintel_survival_darkaether_artifact_10", #"zmintel_survival_darkaether_artifact_11", #"zmintel_survival_darkaether_artifact_12", #"zmintel_survival_darkaether_artifact_13", #"zmintel_survival_darkaether_artifact_14", #"zmintel_survival_darkaether_artifact_15", #"zmintel_survival_darkaether_artifact_16"));
    names = IntelPush(names, array(#"zmintel_survival_darkaether_artifact_17", #"zmintel_survival_darkaether_artifact_18", #"zmintel_survival_darkaether_artifact_19", #"zmintel_survival_darkaether_artifact_2", #"zmintel_survival_darkaether_artifact_20", #"zmintel_survival_darkaether_artifact_21", #"zmintel_survival_darkaether_artifact_22", #"zmintel_survival_darkaether_artifact_3", #"zmintel_survival_darkaether_artifact_4", #"zmintel_survival_darkaether_artifact_5", #"zmintel_survival_darkaether_artifact_6", #"zmintel_survival_darkaether_artifact_7", #"zmintel_survival_darkaether_artifact_8", #"zmintel_survival_darkaether_artifact_9", #"zmintel_survival_darkaether_audiolog_1"));
    names = IntelPush(names, array(#"zmintel_survival_darkaether_audiolog_2", #"zmintel_survival_darkaether_audiolog_3", #"zmintel_survival_darkaether_audiolog_4", #"zmintel_survival_darkaether_audiolog_5", #"zmintel_survival_darkaether_audiolog_6", #"zmintel_survival_darkaether_audiolog_7", #"zmintel_survival_darkaether_audiolog_8", #"zmintel_survival_darkaether_audiolog_9", #"zmintel_survival_darkaether_document_1", #"zmintel_survival_darkaether_document_10", #"zmintel_survival_darkaether_document_11", #"zmintel_survival_darkaether_document_12", #"zmintel_survival_darkaether_document_2", #"zmintel_survival_darkaether_document_3", #"zmintel_survival_darkaether_document_4"));
    names = IntelPush(names, array(#"zmintel_survival_darkaether_document_5", #"zmintel_survival_darkaether_document_6", #"zmintel_survival_darkaether_document_7", #"zmintel_survival_darkaether_document_8", #"zmintel_survival_darkaether_document_9", #"zmintel_survival_darkaether_radio_1", #"zmintel_survival_darkaether_radio_10", #"zmintel_survival_darkaether_radio_11", #"zmintel_survival_darkaether_radio_12", #"zmintel_survival_darkaether_radio_13", #"zmintel_survival_darkaether_radio_14", #"zmintel_survival_darkaether_radio_2", #"zmintel_survival_darkaether_radio_3", #"zmintel_survival_darkaether_radio_4", #"zmintel_survival_darkaether_radio_5", #"zmintel_survival_darkaether_radio_6"));
    names = IntelPush(names, array(#"zmintel_survival_darkaether_radio_7", #"zmintel_survival_darkaether_radio_8", #"zmintel_survival_darkaether_radio_9", #"zmintel_survival_maxis_artifact_1", #"zmintel_survival_maxis_artifact_2", #"zmintel_survival_maxis_artifact_3", #"zmintel_survival_maxis_artifact_4", #"zmintel_survival_maxis_artifact_5", #"zmintel_survival_maxis_artifact_6", #"zmintel_survival_maxis_artifact_7", #"zmintel_survival_maxis_artifact_8", #"zmintel_survival_maxis_audiolog_1", #"zmintel_survival_maxis_audiolog_10", #"zmintel_survival_maxis_audiolog_11", #"zmintel_survival_maxis_audiolog_12", #"zmintel_survival_maxis_audiolog_13", #"zmintel_survival_maxis_audiolog_14"));
    names = IntelPush(names, array(#"zmintel_survival_maxis_audiolog_15", #"zmintel_survival_maxis_audiolog_16", #"zmintel_survival_maxis_audiolog_17", #"zmintel_survival_maxis_audiolog_18", #"zmintel_survival_maxis_audiolog_2", #"zmintel_survival_maxis_audiolog_3", #"zmintel_survival_maxis_audiolog_4", #"zmintel_survival_maxis_audiolog_5", #"zmintel_survival_maxis_audiolog_6", #"zmintel_survival_maxis_audiolog_7", #"zmintel_survival_maxis_audiolog_8", #"zmintel_survival_maxis_audiolog_9", #"zmintel_survival_maxis_document_1", #"zmintel_survival_maxis_document_10", #"zmintel_survival_maxis_document_11", #"zmintel_survival_maxis_document_12", #"zmintel_survival_maxis_document_13"));
    names = IntelPush(names, array(#"zmintel_survival_maxis_document_14", #"zmintel_survival_maxis_document_2", #"zmintel_survival_maxis_document_4", #"zmintel_survival_maxis_document_5", #"zmintel_survival_maxis_document_6", #"zmintel_survival_maxis_document_7", #"zmintel_survival_maxis_document_8", #"zmintel_survival_maxis_document_9", #"zmintel_survival_maxis_radio_1", #"zmintel_survival_maxis_radio_10", #"zmintel_survival_maxis_radio_11", #"zmintel_survival_maxis_radio_2", #"zmintel_survival_maxis_radio_3", #"zmintel_survival_maxis_radio_4", #"zmintel_survival_maxis_radio_5", #"zmintel_survival_maxis_radio_6", #"zmintel_survival_maxis_radio_7", #"zmintel_survival_maxis_radio_8"));
    names = IntelPush(names, array(#"zmintel_survival_maxis_radio_9", #"zmintel_survival_omega_artifact_1", #"zmintel_survival_omega_artifact_10", #"zmintel_survival_omega_artifact_11", #"zmintel_survival_omega_artifact_12", #"zmintel_survival_omega_artifact_13", #"zmintel_survival_omega_artifact_14", #"zmintel_survival_omega_artifact_15", #"zmintel_survival_omega_artifact_16", #"zmintel_survival_omega_artifact_17", #"zmintel_survival_omega_artifact_18", #"zmintel_survival_omega_artifact_19", #"zmintel_survival_omega_artifact_2", #"zmintel_survival_omega_artifact_20", #"zmintel_survival_omega_artifact_3", #"zmintel_survival_omega_artifact_4", #"zmintel_survival_omega_artifact_5"));
    names = IntelPush(names, array(#"zmintel_survival_omega_artifact_6", #"zmintel_survival_omega_artifact_7", #"zmintel_survival_omega_artifact_8", #"zmintel_survival_omega_artifact_9", #"zmintel_survival_omega_audiolog_1", #"zmintel_survival_omega_audiolog_10", #"zmintel_survival_omega_audiolog_11", #"zmintel_survival_omega_audiolog_12", #"zmintel_survival_omega_audiolog_13", #"zmintel_survival_omega_audiolog_14", #"zmintel_survival_omega_audiolog_15", #"zmintel_survival_omega_audiolog_16", #"zmintel_survival_omega_audiolog_17", #"zmintel_survival_omega_audiolog_18", #"zmintel_survival_omega_audiolog_19", #"zmintel_survival_omega_audiolog_2", #"zmintel_survival_omega_audiolog_20"));
    names = IntelPush(names, array(#"zmintel_survival_omega_audiolog_21", #"zmintel_survival_omega_audiolog_22", #"zmintel_survival_omega_audiolog_23", #"zmintel_survival_omega_audiolog_24", #"zmintel_survival_omega_audiolog_3", #"zmintel_survival_omega_audiolog_4", #"zmintel_survival_omega_audiolog_5", #"zmintel_survival_omega_audiolog_6", #"zmintel_survival_omega_audiolog_7", #"zmintel_survival_omega_audiolog_8", #"zmintel_survival_omega_audiolog_9", #"zmintel_survival_omega_document_1", #"zmintel_survival_omega_document_10", #"zmintel_survival_omega_document_11", #"zmintel_survival_omega_document_12", #"zmintel_survival_omega_document_13", #"zmintel_survival_omega_document_14"));
    names = IntelPush(names, array(#"zmintel_survival_omega_document_15", #"zmintel_survival_omega_document_16", #"zmintel_survival_omega_document_17", #"zmintel_survival_omega_document_18", #"zmintel_survival_omega_document_19", #"zmintel_survival_omega_document_2", #"zmintel_survival_omega_document_3", #"zmintel_survival_omega_document_5", #"zmintel_survival_omega_document_6", #"zmintel_survival_omega_document_7", #"zmintel_survival_omega_document_8", #"zmintel_survival_omega_document_9", #"zmintel_survival_omega_radio_1", #"zmintel_survival_omega_radio_2", #"zmintel_survival_omega_radio_3", #"zmintel_survival_omega_radio_4", #"zmintel_survival_omega_radio_5", #"zmintel_survival_omega_radio_6"));
    names = IntelPush(names, array(#"zmintel_survival_omega_radio_7", #"zmintel_survival_omega_radio_8", #"zmintel_survival_omega_radio_9", #"zmintel_survival_requiem_artifact_1", #"zmintel_survival_requiem_artifact_10", #"zmintel_survival_requiem_artifact_11", #"zmintel_survival_requiem_artifact_12", #"zmintel_survival_requiem_artifact_13", #"zmintel_survival_requiem_artifact_14", #"zmintel_survival_requiem_artifact_15", #"zmintel_survival_requiem_artifact_16", #"zmintel_survival_requiem_artifact_17", #"zmintel_survival_requiem_artifact_18", #"zmintel_survival_requiem_artifact_19", #"zmintel_survival_requiem_artifact_2", #"zmintel_survival_requiem_artifact_20", #"zmintel_survival_requiem_artifact_21"));
    names = IntelPush(names, array(#"zmintel_survival_requiem_artifact_22", #"zmintel_survival_requiem_artifact_23", #"zmintel_survival_requiem_artifact_3", #"zmintel_survival_requiem_artifact_4", #"zmintel_survival_requiem_artifact_5", #"zmintel_survival_requiem_artifact_6", #"zmintel_survival_requiem_artifact_7", #"zmintel_survival_requiem_artifact_8", #"zmintel_survival_requiem_artifact_9", #"zmintel_survival_requiem_audiolog_1", #"zmintel_survival_requiem_audiolog_10", #"zmintel_survival_requiem_audiolog_11", #"zmintel_survival_requiem_audiolog_12", #"zmintel_survival_requiem_audiolog_13", #"zmintel_survival_requiem_audiolog_14", #"zmintel_survival_requiem_audiolog_15"));
    names = IntelPush(names, array(#"zmintel_survival_requiem_audiolog_16", #"zmintel_survival_requiem_audiolog_17", #"zmintel_survival_requiem_audiolog_18", #"zmintel_survival_requiem_audiolog_19", #"zmintel_survival_requiem_audiolog_2", #"zmintel_survival_requiem_audiolog_20", #"zmintel_survival_requiem_audiolog_21", #"zmintel_survival_requiem_audiolog_22", #"zmintel_survival_requiem_audiolog_23", #"zmintel_survival_requiem_audiolog_24", #"zmintel_survival_requiem_audiolog_3", #"zmintel_survival_requiem_audiolog_4", #"zmintel_survival_requiem_audiolog_5", #"zmintel_survival_requiem_audiolog_6", #"zmintel_survival_requiem_audiolog_7", #"zmintel_survival_requiem_audiolog_8"));
    names = IntelPush(names, array(#"zmintel_survival_requiem_audiolog_9", #"zmintel_survival_requiem_document_1", #"zmintel_survival_requiem_document_10", #"zmintel_survival_requiem_document_11", #"zmintel_survival_requiem_document_12", #"zmintel_survival_requiem_document_13", #"zmintel_survival_requiem_document_14", #"zmintel_survival_requiem_document_15", #"zmintel_survival_requiem_document_16", #"zmintel_survival_requiem_document_17", #"zmintel_survival_requiem_document_18", #"zmintel_survival_requiem_document_19", #"zmintel_survival_requiem_document_2", #"zmintel_survival_requiem_document_20", #"zmintel_survival_requiem_document_21", #"zmintel_survival_requiem_document_22"));
    names = IntelPush(names, array(#"zmintel_survival_requiem_document_23", #"zmintel_survival_requiem_document_24", #"zmintel_survival_requiem_document_25", #"zmintel_survival_requiem_document_26", #"zmintel_survival_requiem_document_3", #"zmintel_survival_requiem_document_4", #"zmintel_survival_requiem_document_5", #"zmintel_survival_requiem_document_6", #"zmintel_survival_requiem_document_7", #"zmintel_survival_requiem_document_8", #"zmintel_survival_requiem_document_9", #"zmintel_survival_requiem_radio_1", #"zmintel_survival_requiem_radio_10", #"zmintel_survival_requiem_radio_11", #"zmintel_survival_requiem_radio_12", #"zmintel_survival_requiem_radio_13", #"zmintel_survival_requiem_radio_14"));
    names = IntelPush(names, array(#"zmintel_survival_requiem_radio_15", #"zmintel_survival_requiem_radio_2", #"zmintel_survival_requiem_radio_3", #"zmintel_survival_requiem_radio_4", #"zmintel_survival_requiem_radio_5", #"zmintel_survival_requiem_radio_6", #"zmintel_survival_requiem_radio_7", #"zmintel_survival_requiem_radio_8", #"zmintel_survival_requiem_radio_9", #"zmintel_tungsten_darkaether_artifact_1", #"zmintel_tungsten_darkaether_artifact_2", #"zmintel_tungsten_darkaether_artifact_3", #"zmintel_tungsten_darkaether_artifact_4", #"zmintel_tungsten_maxis_audiolog_1", #"zmintel_tungsten_maxis_audiolog_2", #"zmintel_tungsten_maxis_audiolog_3", #"zmintel_tungsten_maxis_document_1"));
    names = IntelPush(names, array(#"zmintel_tungsten_omega_audiolog_1", #"zmintel_tungsten_omega_audiolog_2", #"zmintel_tungsten_omega_audiolog_3", #"zmintel_tungsten_omega_audiolog_4", #"zmintel_tungsten_omega_document_1", #"zmintel_tungsten_omega_document_2", #"zmintel_tungsten_omega_document_3", #"zmintel_tungsten_omega_document_4", #"zmintel_tungsten_omega_document_5", #"zmintel_tungsten_omega_document_6", #"zmintel_tungsten_omega_document_7", #"zmintel_tungsten_omega_document_8", #"zmintel_tungsten_omega_document_9", #"zmintel_tungsten_requiem_artifact_1", #"zmintel_tungsten_requiem_artifact_2", #"zmintel_tungsten_requiem_artifact_3", #"zmintel_tungsten_requiem_artifact_4"));
    names = IntelPush(names, array(#"zmintel_tungsten_requiem_artifact_5", #"zmintel_tungsten_requiem_audiolog_1", #"zmintel_tungsten_requiem_audiolog_2", #"zmintel_tungsten_requiem_audiolog_3", #"zmintel_tungsten_requiem_audiolog_4", #"zmintel_tungsten_requiem_document_1", #"zmintel_tungsten_requiem_document_2", #"zmintel_tungsten_requiem_document_3", #"zmintel_tungsten_requiem_document_4", #"zmintel_tungsten_requiem_document_5", #"zmintel_tungsten_requiem_document_6"));
    return names;
}

IntelPush(names, arr)
{
    foreach (x in arr)
        names[names.size] = x;
    return names;
}
